services:
  db:
    image: postgres:16-alpine
    container_name: rt_db
    restart: always
    network_mode: "host"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - rt_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: rt_backend
    restart: always
    network_mode: "host"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: rt_frontend
    restart: always
    network_mode: "host"

volumes:
  rt_data:
